Compatibility bfw v3.0.0-rc11

diff --git a/test/run/installer b/test/run/installer
--- a/test/run/installer
+++ b/test/run/installer
@@ -15,16 +15,44 @@ php composer.phar install
 
 echo '\033[0;33mBFW Install and module\033[0m'
 ./vendor/bin/bfwInstall
-./vendor/bin/bfwInstallModules
+./vendor/bin/bfwAddMod -a
 
 echo '\033[0;33mCopy module test skeleton files\033[0m'
 cd ../
 mv install/app/config/bfw/modules.php install/app/config/bfw/modules.php.original
 cp -Rf skeleton/app/* install/app/
+cd install
 
+echo '\033[0;33mEnable all modules\033[0m'
+./vendor/bin/bfwEnMod -a
+
+DIRECTORY=`pwd`
+
+echo -n '\033[0;33mCheck module bfw-fastroute is available ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/available/bfw-fastroute" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
+
+echo -n '\033[0;33mCheck module bfw-fastroute is enabled ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/enabled/bfw-fastroute" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
+
+echo -n '\033[0;33mCheck module displayRoute is enabled ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/enabled/displayRoute" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
 
 echo '\033[0;33mRun php integrated web server\033[0m'
-cd install
 php -S localhost:8000 -t web web/index.php &
 
 echo '\033[0;33mWait 5s web server is running\033[0m'
